GET {{url}}/plantsa
###
GET {{url}}/plantsa/1
###
GET {{url}}/plantsa/type/Rose
###
POST {{url}}/plantsa
Content-Type: application/json

{
  "plantType": "FruitTree",
  "name": "Cherry Tree",
  "price": 155.50,
  "maxHeight": 200


}
###
PUT {{url}}/plantsa/6
Content-Type: application/json

{
  "plantType": "FruitTree",
  "name": "Pear Tree",
  "price": 195.50,
  "maxHeight": 300
  }
###
DELETE {{url}}/plantsa/6
###
PUT {{url}}/plantsa/addReseller/1/2